version: "3.7"

networks:
  weatherapi-network:
  
services:
  weatherapi-sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "Qwerty1234"
        ACCEPT_EULA: "Y"
    networks:
      - weatherapi-network